### PR TITLE
update sass-graph and recursively track imports

### LINKED ISSUE #3: track deeper levels of import
hey @berstend,
Nice work!
Currently it can only get one level om @import. Can this be improved to catch deeper levels of @import.
For example

**a.scss**

```
@import 'b';
```

**b.scss**

```
@import 'c';
```

**c.scss**

```
//some SCSS
```

if I change **a.scss** or **b.scss** it passes the filter and compiles **a.scss**. But if I make any change to **c.scss** it wont pass the filter block and wont compile **a.scss**.

did I make myself clear?

### PR DESCRIPTION
**Pull request by safareli**
fixes #3

### CODE REVIEW

**Comment by kevin-smets** [comment]
Any news on this?

**Comment by raff-r** [comment]
I too would love to see this merged... helps alot with my current project

**Comment by glen-84** [comment]
@berstend Do you have any plans to continue working on this plug-in?

BTW, the latest version of sass-graph is now 2.1.1.

**Comment by fent** [comment]
This still hasn't been merged...

**Comment by fent** [comment]
Thank you 😮

**Comment by berstend** [comment]
@glen-84 @fent  Sorry everyone!

I was totally swamped with work and didn't pay attention to the GH notifications.
I come bearing ~~gifts~~ [tests](https://github.com/berstend/gulp-sass-inheritance/tree/master/test)! 😅 

I've incorporated this PR among others in a fresh **[v1.1.0](https://github.com/berstend/gulp-sass-inheritance#v110-2017-05-13)** release that has also been published on [NPM](https://www.npmjs.com/package/gulp-sass-inheritance).

I make sure to be more active on PRs from now on. Thanks!

**Pull request merged**
